### ISSUE TITLE
Setting a min/max limit on multiselect

### ISSUE THREAD

**Issue by CapitanFindusFI** [CapitanFindusFI/react-autocomplete-multiselect#1]
Starting from `selectionMax` and `selectionMin` properties from the Select component, use `selectionMax` to disable selecting more items and `selectionMin` to enable/disable confirmation button when the number of selected elements is lower than the minimum.

Both should be defaulted to 0

**Comment by Trafitto** [comment]
Seems made for me, let me do it :hand:

**Comment by Trafitto** [comment]
I start working on it now I hope to complete it by tonight

**Comment by Trafitto** [comment]
Check this out #7

**Comment by CapitanFindusFI** [comment]
[Closed here](https://github.com/CapitanFindusFI/react-autocomplete-multiselect/pull/7)
