### ISSUE TITLE
Deselecting an object does not always remove it from the list of selected objects

### ISSUE THREAD

**Issue by Trafitto** [CapitanFindusFI/react-autocomplete-multiselect#3]
If you select and deselect objects a couple of times, when you deselect all of them there is always one inside selectedItems

![image](https://user-images.githubusercontent.com/17903940/135713639-25dc3ea8-d1ac-4ab5-9055-886c435a250c.png)

if it's not a problem for you I can fix it after fixing the other issue

**Comment by CapitanFindusFI** [comment]
[Closed here](https://github.com/CapitanFindusFI/react-autocomplete-multiselect/pull/8)
